apiVersion: v0.1.0
envs:
- name: dev
  path: .xlr8s/envs/dev/env.yaml
- name: dev1
  path: .xlr8s/envs/dev1/env.yaml
- name: dv1
  path: .xlr8s/envs/dv1/env.yaml
git: null
modules:
  k8stools:
  - module: git@github.com:xebiaww-apps/helm-xebia-opa-gatekeeper.git
    ref:
      branch: v3.24.7
  - module: git@github.com:xebiaww-apps/helm-xebia-opa-gatekeeper-constraints.git
    ref:
      branch: v3.2.5
vars:
  apps: null
  policy:
    K8sAllowedRepos: []
    K8sBlockNpLb: []
    K8sCapsOnReplica: []
    K8sDisableHostNetworking: []
    K8sPodPriority: []
    K8sRequiredProbes: []
    K8sRunAsNonRoot: []
