{{ $v := .Values.K8sRunAsNonRoot }}

{{range $j, $constraint := $v }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRunAsNonRoot
metadata:
  name: {{$constraint.name}}
  labels:
    severity: {{$constraint.severity}}
spec:
  enforcementAction: {{$constraint.enforcementAction}}
  
  match:

    {{if $constraint.filters.namespaces  }}  
    namespaces: {{- toYaml $constraint.filters.namespaces | nindent 6 }}
    {{end}}
    
    {{if $constraint.filters.excludedNamespaces  }}  
    excludedNamespaces: {{- toYaml $constraint.filters.excludedNamespaces | nindent 6 }}
    {{end}}

    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
    
    labelSelector:
      matchLabels: 
        {{- toYaml $constraint.filters.labels  | nindent 8 }}
      

{{if $constraint.params }}
  parameters: {{- toYaml $constraint.params | nindent 4 }}
{{end}}
  
---      
{{ end }}